---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "prometheus-aduser-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-aduser-exporter.name" . }}
    chart: {{ template "prometheus-aduser-exporter.chart" . }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "prometheus-aduser-exporter.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "prometheus-aduser-exporter.fullname" . }}
      labels:
        app: {{ template "prometheus-aduser-exporter.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
          - name: AD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secret.name | quote }}
                key: AdUserPassword
          {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 10 }}
          {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.nodeSelector | nindent 10 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
      {{- toYaml .Values.affinity | nindent 10 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
      {{- toYaml .Values.tolerations | nindent 10 }}
      {{- end }}