apiVersion: v1
kind: Service
metadata:
  name: {{ template "prometheus-aduser-exporter.fullname" . }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "prometheus-aduser-exporter.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ template "prometheus-aduser-exporter.chart" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  selector:
    app: {{ template "prometheus-aduser-exporter.fullname" . }}
